### ISSUE TITLE
Won't Start The Rails Recipe

### ISSUE THREAD

**Issue by brycethornton** [alloy/kicker#6]
I'm getting this error when trying to start the built-in rails recipe. Any ideas?

```
/Users/bryce/Sites/eventstart>kicker -r rails
/System/Library/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_import.rb:751:in `method_missing': undefined method `alias_method_chain' for String (NoMethodError)
    from /Users/bryce/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:9:in `included'
    from /Users/bryce/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:6:in `class_eval'
    from /Users/bryce/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:6:in `included'
    from /Users/bryce/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string.rb:24:in `include'
    from /Users/bryce/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string.rb:24
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/bryce/.gem/ruby/1.8/gems/kicker-2.2.2/lib/kicker/recipes/rails.rb:111
     ... 12 levels...
    from /Users/bryce/.gem/ruby/1.8/gems/kicker-2.2.2/lib/kicker.rb:13:in `run'
    from /Users/bryce/.gem/ruby/1.8/gems/kicker-2.2.2/bin/kicker:5
    from /Users/bryce/.gem/ruby/1.8/bin/kicker:19:in `load'
    from /Users/bryce/.gem/ruby/1.8/bin/kicker:19
```

**Comment by alloy** [comment]
Make the Rails recipe work with ActiveSupport 2.3.5. Closed by 86f8839893e0ea756403a22ec39819bfdf24cc95.

In 2.3.5 the String OutputSafety module has been added, which depends on
alias_method_chain. However, the file that defines the OutputSafety module does
not require the file that defines alias_method_chain.

**Comment by alloy** [comment]
Just pushed a new gem to gemcutter with this fix: http://gemcutter.org/gems/kicker

Thanks for reporting!
