### ISSUE TITLE
Fails with Listener 2.0

### ISSUE THREAD

**Issue by dreki** [alloy/kicker#47]
```
undefined method `change' for #<Listen::Listener>
```

**Comment by Manfred** [comment]
Kicker is only supposed to work with Listen ~> 1.3. Does installing the new prerelase version fix this for you?

gem install kicker —pre
